#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 23 常見問題與建議 (4)
# Url: https://ithelp.ithome.com.tw/articles/10193954
# Licence: MIT
#####################################

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm